import styles from './Main.module.scss';

function Main() {
  return (
    <main className={styles.Main}>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
      <p>Pariatur exercitation fugiat minim reprehenderit consectetur officia. Ut velit exercitation elit do esse. Occaecat irure labore pariatur deserunt aliquip. Voluptate cillum do aliquip cupidatat aliquip non aute aute incididunt sint tempor minim. Ullamco adipisicing minim dolore aliquip. Ad incididunt nisi et esse ipsum excepteur irure amet occaecat reprehenderit.</p>
    </main>
  )
}

export default Main;